namespace GunGiBoardGameWPF.GameHolder.Enum
{
	public enum Phase
	{
		SELECT_COLOR,
		SELECT_LEVEL,
		SELECT_RECOMMEND_OR_MANUAL_ARRANGEMENT,
		COUNTDOWN_FOR_GAMING,
		BEFORE_GAMING_BUFFER_ZONE,
		GAMING_BUFFER_ZONE,
	}
}
