namespace GunGiBoardGameWPF.GameHolder
{
	public class Constant
	{
		public const string FONT_PATH = @"Font\\NotoSansTC-Bold.otf";
		public const double WINDOW_SIZE_WIDTH = 1024;
		public const double WINDOW_SIZE_HEIGHT = 768;
		public const string WINDOW_TITLE = "GunGi";
		public const int DELAY=500;
		public const int COLOR_AND_LEVEL_TITLE_X = 350;
		public const int ARRANGEMENT_TITLE_X = 225;
		public const int TITLE_Y = 100;
		public const int LEVEL_BEGINNER_X = 300;
		public const int LEVEL_ELEMENTARY_X = 400;
		public const int LEVEL_INTERMEDIATE_X = 500;
		public const int LEVEL_ADVANCED_X = 600;
		public const int LEVEL_Y = 300;
		public const int LEVEL_BLOCK_SIZE = 99;
		public const string ALLKOMA = "帥大中小侍忍槍砦馬兵弓砲筒謀";
		public const int RECOMMENDED_ARRANGEMENT_BUTTON_X = 375;
		public const int MANUAL_ARRANGEMENT_BUTTON_X = 525;
		public const int ARRANGEMENT_BUTTON_Y = 300;
		public const int ARRANGEMENT_BUTTON_SIZE = 149;
		public const int PREPARE_FOR_GAMING_TIME = 1;
		public const int BOARD_WIDTH = 550;
		public const int BOARD_HEIGHT = 550;
		public const int BOARD_X = 237;
		public const int BOARD_Y = 109;
		public const int BLOCK_SIZE = 60;
		public const int OWN_KOMADAI_X = 788;
		public const int OWN_KOMADAI_Y = 492;
		public const int OPPONENT_KOMADAI_X = 69;
		public const int OPPONENT_KOMADAI_Y = 109;
		public const int KOMADAI_SIZE = 167;
		public const int KOMA_ON_OWN_KOMADAI_X = 790;
		public const int KOMA_ON_OWN_KOMADAI_Y = 493;
		public const int KOMA_ON_OPPONENT_KOMADAI_X =194;
		public const int KOMA_ON_OPPONENT_KOMADAI_Y = 234;
		public const int KOMA_SIZE = 40;
		public const int TIMER_X = 850;
		public const int TIMER_Y = 109;
		public const int TIMER_WIDTH = 120;
		public const int TIMER_HEIGHT = 240;
		public const int TIMER_SIZE = 118;
		public const int REMAINING_TIME = 600;
		public const int SUMI_BUTTON_X = 462;
		public const int SUMI_BUTTON_Y = 665;
		public const int SUMI_BUTTON_WIDTH = 100;
		public const int SUMI_BUTTON_HEIGHT = 100;
		public const int CPU_DECLARE_SUMI_TARGET_PERCENTAGE = 65;
		public const int SECOND_DAN = 5;
		public const int THIRD_DAN = 10;
		public const int CAPTURE_OR_CONTROL_X = 276;
		public const int CAPTURE_OR_CONTROL_Y = 300;
		public const int CAPTURE_OR_CONTROL_WIDTH = 476;
		public const int CAPTURE_OR_CONTROL_HEIGHT = 150;
		public const int CAPTURE_BUTTON_X = 376;
		public const int CAPTURE_BUTTON_Y = 388;
		public const int CAPTURE_BUTTON_WIDTH = 100;
		public const int CAPTURE_BUTTON_HEIGHT = 50;
		public const int ANOTHER_ROUND_OR_EXIT_X = CAPTURE_OR_CONTROL_X;
		public const int ANOTHER_ROUND_OR_EXIT_Y = CAPTURE_OR_CONTROL_Y;
		public const int ANOTHER_ROUND_OR_EXIT_WIDTH = CAPTURE_OR_CONTROL_WIDTH;
		public const int ANOTHER_ROUND_OR_EXIT_HEIGHT = CAPTURE_OR_CONTROL_HEIGHT;
		public const int ANOTHER_ROUND_BUTTON_X = CAPTURE_BUTTON_X;
		public const int ANOTHER_ROUND_BUTTON_Y = CAPTURE_BUTTON_Y;
		public const int ANOTHER_ROUND_BUTTON_WIDTH = CAPTURE_BUTTON_WIDTH;
		public const int ANOTHER_ROUND_BUTTON_HEIGHT = CAPTURE_BUTTON_HEIGHT;
		public const int MUTINY_X = CAPTURE_OR_CONTROL_X;
		public const int MUTINY_Y = CAPTURE_OR_CONTROL_Y;
		public const int MUTINY_WIDTH = CAPTURE_OR_CONTROL_WIDTH;
		public const int MUTINY_HEIGHT = CAPTURE_OR_CONTROL_HEIGHT;
		public const int MUTINY_BUTTON_X = CAPTURE_BUTTON_X;
		public const int MUTINY_BUTTON_Y = CAPTURE_BUTTON_Y;
		public const int MUTINY_BUTTON_WIDTH = CAPTURE_BUTTON_WIDTH;
		public const int MUTINY_BUTTON_HEIGHT = CAPTURE_BUTTON_HEIGHT;
	}

}
